spring:
  config:
    import: optional:application-secret.yml
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: tester
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      username: default
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}
      ssl:
        enabled: true

# MUST BE DIFFERENT to application-prod
paseto:
  secret: "Z9fQmA7Lx3P2sJ8kTnWcR4D0eE6VhU5BKyM1HqNopYtSaIbFdrCg"